= Build iOS checklist app that satisfies all of my requirements
Hank Lin; thesolidarityengineer@gmail.com; 4-7-2026

== Description
*Context*: After experimenting and paying for various checklist apps on iOS store, I encountered various combination of shortcomings with each app along with agreeing with various apps respective reviews that highlight their known shortcomings.

*Task*: Build iOS checklist app that satisfies all of my requirements

.*User Story*: As a user with Hank's preferences,
* I want a simple interface to add new item on checklist, so that I can quickly add new items
* I want a reoccuring backlog of items with tags, so that I can place them onto a list without needing to retype
* I want a simple interface to batch select populate a checklist from a backlog, so that I can reduce typing
* I want a one off backlog of items, so I can have a jottery backlog of items to be worked on later
* I want each item to support having a detailed notes option, so I can place more specific instruction or information on the item if needed
* I want a sidebar to access pages, so that I can organize groups of checklists
* I want a re-arrange mode, so that the touch experience doesn't clash from movement mode being on all the time
* I want a check/uncheck all option, so that I can reset a checklist when needed
* I want an optional display mode to represent a item is in progress, so that collaborators can see what is in progress

*Acceptance Criteria*: Definition of reaching the end (based on https://cucumber.io/docs/terms/user-story#acceptance-criteria-using-cucumber-language)

[source,gherkin]
----
Feature: Simple interface to add new item on checklist
  Scenario: Adding to checklist
    Given I have an empty or populated checklist
    When I click on the plus sign
    Then I get a new entry item that I can type out
----

[source,gherkin]
----
Feature: Reoccuring backlog of items with tags
  Scenario: Viewing and editing reoccuring backlog
    Given I have a reoccuring backlog of items
    And I tag them
    When I click select tags
    Then I should see items that have the selected tags
----

[source,gherkin]
----
Feature: Simple interface to batch select populate a checklist from a backlog
  Scenario: Adding to checklist from batch selecting items from backlog
    Given I have an empty or populated checklist
    And backlog items
    When I click on the batch plus sign
    And I select multiple backlog items
    And click add
    Then I see the selected backlog items added to the checklist
----

[source,gherkin]
----
Feature: One off backlog of items
  Scenario: Viewing and editing one off backlog
    Given I have a one off backlog of items
    When I go to one off backlog screen
    Then I should see all my one off backlog items
----

[source,gherkin]
----
Feature: Each item to support having a detailed notes option
  Scenario: Adding note
    Given I have a checklist item
    When I swipe to unveil note editing button
    And I click on note button
    Then I see a note screen to fill in notes to the item
    When I click save
    And I look at note again
    Then I see that the note has been saved
----

[source,gherkin]
----
Feature: Sidebar to access pages
  Scenario: Accessing pages
    Given I am on the main screen
    When I click on a different page
    Then I see a different page's set of checklists

  Scenario: Adding pages
    Given I am on the main screen
    When I click on plus button to add a page
    Then I see a page added on the side bar
----

[source,gherkin]
----
Feature: Re-arrange mode
  Scenario: Re-arranging items in a checklist
    Given I am on a checklist with multiple items
    When I click on re-arrange
    Then I am able to re-arrange items on a checklist
----

[source,gherkin]
----
Feature: Check/uncheck all option
  Scenario: Reseting a checklist
    Given I am on a checklist with multiple items
    When I click on check/uncheck all
    Then all of the items in the checklist become checked/unchecked
----

[source,gherkin]
----
Feature: Optional display mode to represent a item is in progress
  Scenario: Marking an item that it is in progress
    Given I am on a checklist with atleast 1 item
    When I swipe right on the item
    And click in progress button
    Then the item will display that it is in progress
----

*Solution/Result*: In progress

*Implication*: Where else can I browse through the community and get feedback to create something better?

== Engineer Concerns:
*Prior relevant experience*: Lots of React frontend experience 0 iOS experience

*Doing for first time*: Everything involved should have been solved engineering problems

*Lessons Learned*:

*Engineering constraints*:

.*Complexity factors*:
* How to prove work is done: Manually interact with the app and ensure it passes standards of good quality
* Domain Changes: Create concepts of checklist interaction and necessary features of interaction
* Event Changes: None
* System Changes: None

== Resources:
[unordered]
tutorial::
* https://developer.apple.com/tutorials/develop-in-swift/#welcome
how-to:: ...
explanation:: ...
reference:: ...


== Thought Process:

'''

*Accomplished*: I have no reference to take a guess on the project since I have no iOS experience. I input into Claude Code the prompt "I want to code an iOS checklist app" and then also prompted for SwiftUI framework and all the possible features Claude Code inferred I might want. I got back 9 swift files and a plist file that gives me a rough idea how iOS apps written in Swift are structured. It's very clear that the structure takes inspiration from a common ancestor to React or .NET MVC projects. I double check with https://developer.apple.com/tutorials/develop-in-swift/#welcome and https://developer.apple.com/documentation/ so I can understand the syntactic output that Claude gave me. After analyzing, it is very clear that the underlying data modeling and data structures that Claude Code gave me does not have enough conceptualization to support the user story.

*What's next*: Design data modeling, data structure, and expertise breakdown to make it possible to fulfill the user stories

Tue Apr  7 14:31:53 EDT 2026

'''
